# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "ECONAOS: ecological marine data and the Open Science"
email: annalisa.minelli@ve.ismar.cnr.it
description: > # this means to ignore newlines until "baseurl:"
  Open Science principles are more and more pervasive in a scientist's life.
  European Union and other important international organisations are
  progressively recognising the importance of open science (that includes
  open source, open data, open access and so on). The Institute for Marine 
  Science at the Italian National Council of Research makes part of a larger
  network of Long Term Ecological Data, and provides a great variety of 
  oceanographic data. We focus on North Adriatic area and our aim is to 
  implement a strategy to open all the lifecycle of our research: starting 
  from the collection of data, to the publication of results. In this context, 
  the blog wants to be a newsletter to keep us and you all update about our
  activities and ideas. Stay tuned!
baseurl: "/test" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  CNR-ISMAR
facebook_username: ProgettoRitmare

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
